# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vencalendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calendar(object):
    def setupUi(self, calendar):
        calendar.setObjectName("calendar")
        calendar.resize(320, 188)
        self.calendar_2 = QtWidgets.QCalendarWidget(calendar)
        self.calendar_2.setGeometry(QtCore.QRect(0, 0, 312, 183))
        self.calendar_2.setObjectName("calendar_2")

        self.retranslateUi(calendar)
        QtCore.QMetaObject.connectSlotsByName(calendar)

    def retranslateUi(self, calendar):
        _translate = QtCore.QCoreApplication.translate
        calendar.setWindowTitle(_translate("calendar", "Dialog"))
