# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaSalir.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_btnBox(object):
    def setupUi(self, btnBox):
        btnBox.setObjectName("btnBox")
        btnBox.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(btnBox)
        self.buttonBox.setGeometry(QtCore.QRect(110, 140, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.lblMenSalir = QtWidgets.QLabel(btnBox)
        self.lblMenSalir.setGeometry(QtCore.QRect(70, 90, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblMenSalir.setFont(font)
        self.lblMenSalir.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMenSalir.setObjectName("lblMenSalir")
        self.lblimgSalir = QtWidgets.QLabel(btnBox)
        self.lblimgSalir.setGeometry(QtCore.QRect(30, 80, 61, 61))
        self.lblimgSalir.setText("")
        self.lblimgSalir.setPixmap(QtGui.QPixmap("img/warning.png"))
        self.lblimgSalir.setScaledContents(True)
        self.lblimgSalir.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblimgSalir.setObjectName("lblimgSalir")

        self.retranslateUi(btnBox)
        self.buttonBox.accepted.connect(btnBox.accept)
        self.buttonBox.rejected.connect(btnBox.reject)
        QtCore.QMetaObject.connectSlotsByName(btnBox)

    def retranslateUi(self, btnBox):
        _translate = QtCore.QCoreApplication.translate
        btnBox.setWindowTitle(_translate("btnBox", "Dialog"))
        self.lblMenSalir.setText(_translate("btnBox", "¿Está seguro de querer salir?"))

