# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaAbout.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_btnBoxAbout(object):
    def setupUi(self, btnBoxAbout):
        btnBoxAbout.setObjectName("btnBoxAbout")
        btnBoxAbout.resize(629, 424)
        btnBoxAbout.setModal(True)
        self.buttonBoxAbout = QtWidgets.QDialogButtonBox(btnBoxAbout)
        self.buttonBoxAbout.setGeometry(QtCore.QRect(270, 200, 71, 32))
        self.buttonBoxAbout.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxAbout.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBoxAbout.setObjectName("buttonBoxAbout")
        self.lblMenAbout = QtWidgets.QLabel(btnBoxAbout)
        self.lblMenAbout.setGeometry(QtCore.QRect(50, 90, 541, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblMenAbout.setFont(font)
        self.lblMenAbout.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMenAbout.setObjectName("lblMenAbout")

        self.retranslateUi(btnBoxAbout)
        self.buttonBoxAbout.accepted.connect(btnBoxAbout.accept)
        self.buttonBoxAbout.rejected.connect(btnBoxAbout.reject)
        QtCore.QMetaObject.connectSlotsByName(btnBoxAbout)

    def retranslateUi(self, btnBoxAbout):
        _translate = QtCore.QCoreApplication.translate
        btnBoxAbout.setWindowTitle(_translate("btnBoxAbout", "Dialog"))
        self.lblMenAbout.setText(_translate("btnBoxAbout", "\"Logo de la empresa, Versión del programa :0.0.1, Martín Sieiro Álvarez\""))
