# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaAviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_btnBoxAccion(object):
    def setupUi(self, btnBoxAccion):
        btnBoxAccion.setObjectName("btnBoxAccion")
        btnBoxAccion.resize(400, 300)
        btnBoxAccion.setModal(True)
        self.buttonBoxAccion = QtWidgets.QDialogButtonBox(btnBoxAccion)
        self.buttonBoxAccion.setGeometry(QtCore.QRect(110, 180, 161, 32))
        self.buttonBoxAccion.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxAccion.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBoxAccion.setObjectName("buttonBoxAccion")
        self.lblMenAccion = QtWidgets.QLabel(btnBoxAccion)
        self.lblMenAccion.setGeometry(QtCore.QRect(40, 130, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblMenAccion.setFont(font)
        self.lblMenAccion.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMenAccion.setObjectName("lblMenAccion")
        self.lblimgAccion = QtWidgets.QLabel(btnBoxAccion)
        self.lblimgAccion.setGeometry(QtCore.QRect(170, 60, 61, 61))
        self.lblimgAccion.setText("")
        self.lblimgAccion.setPixmap(QtGui.QPixmap(":/warning2/warning2.png"))
        self.lblimgAccion.setScaledContents(True)
        self.lblimgAccion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblimgAccion.setObjectName("lblimgAccion")

        self.retranslateUi(btnBoxAccion)
        self.buttonBoxAccion.accepted.connect(btnBoxAccion.accept)
        self.buttonBoxAccion.rejected.connect(btnBoxAccion.reject)
        QtCore.QMetaObject.connectSlotsByName(btnBoxAccion)

    def retranslateUi(self, btnBoxAccion):
        _translate = QtCore.QCoreApplication.translate
        btnBoxAccion.setWindowTitle(_translate("btnBoxAccion", "Dialog"))
        self.lblMenAccion.setText(_translate("btnBoxAccion", "¿Está seguro de querer realizar esta acción?"))
import avisoAccion_rc
import avisoSalir_rc
